name: Amul Watch

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: amul-watch
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: python -m playwright install chromium

      - name: Add random jitter
        run: sleep $((RANDOM % 10))

      - name: Run watcher
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          SMTP_HOST:          ${{ secrets.SMTP_HOST }}
          SMTP_PORT:          ${{ secrets.SMTP_PORT }}
          SMTP_USER:          ${{ secrets.SMTP_USER }}
          SMTP_PASS:          ${{ secrets.SMTP_PASS }}
          EMAIL_TO:           ${{ secrets.EMAIL_TO }}
          EMAIL_FROM:         ${{ secrets.EMAIL_FROM }}
          FORCE_ALERT:        ${{ vars.FORCE_ALERT }}
        run: python amul_watch.py